name: "Python Tests"
on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run python tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Setup Python 3.x
        uses: "actions/setup-python@v5"
        with:
          python-version: 3.x
      - name: Tests
        run: uv run pytest tests
